after-login-command = []
after-startup-command = []
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false
[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       100
    outer.bottom =     30
    outer.top =        30
    outer.right =      100

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-semicolon = 'mode service'

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.window-title-regex-substring = 'Weixin'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.runningwithcrayons.Alfred-Preferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'tv.parsec.www'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bohemiancoding.sketch3'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.zotero.zotero'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'net.ankiweb.dtop'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'VESTA'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'VMD'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'PyMOL'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.panic.Transmit'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.liguangming.Shadowrocket'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.ovito'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.moonlight-stream.Moonlight'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.firecore.infuse'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Home'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Photos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iBooksX'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.clock'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Console'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.DiskUtility'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Maps'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.weather'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.freeform'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SFSymbols'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.FontBook'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Passwords'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.shortcuts'
run = 'layout floating'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
