# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#10b1fe" }

# Hovered
hovered         = { fg = "#282c34", bg = "#10b1fe", bold = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f9c859", bold = true, italic = true, underline = true }
find_position = { fg = "#ff78f8", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#3fc56b", bg = "#3fc56b" }
marker_cut      = { fg = "#ff6480", bg = "#ff6480" }
marker_marked   = { fg = "#10b1fe", bg = "#10b1fe" }
marker_selected = { fg = "#f9c859", bg = "#f9c859" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#282c34", bg = "#3fc56b" }
count_cut      = { fg = "#282c34", bg = "#ff6480" }
count_selected = { fg = "#282c34", bg = "#f9c859" }

# Border
border_symbol = "│"
border_style  = { fg = "#636d83" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#282c34", bg = "#9f7efe", bold = true }
normal_alt  = { fg = "#9f7efe", bg = "#282c34" }

# Select mode
select_main = { fg = "#282c34", bg = "#10b1fe", bold = true }
select_alt  = { fg = "#10b1fe", bg = "#282c34" }

# Unset mode
unset_main = { fg = "#282c34", bg = "#ce9887", bold = true }
unset_alt  = { fg = "#ce9887", bg = "#282c34" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#636d83" }
perm_type  = { fg = "#10b1fe" }
perm_read  = { fg = "#f9c859" }
perm_write = { fg = "#ff6480" }
perm_exec  = { fg = "#3fc56b" }

# Progress
progress_label  = { fg = "#abb2bf", bold = true }
progress_normal = { fg = "#9f7efe", bg = "#636d83" }
progress_error  = { fg = "#ff6480", bg = "#636d83" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#10b1fe" }
active   = { fg = "#ff78f8", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#10b1fe" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#10b1fe" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#10b1fe" }
title   = {}
hovered = { fg = "#ff78f8", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#282c34" }
cand            = { fg = "#10b1fe" }
rest            = { fg = "#636d83" }
desc            = { fg = "#ff78f8" }
separator       = "  "
separator_style = { fg = "#636d83" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#10b1fe" }
run     = { fg = "#ff78f8" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#282c34", bg = "#abb2bf" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#3fc56b" }
title_warn  = { fg = "#f9c859" }
title_error = { fg = "#ff6480" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#10b1fe" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f9c859" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ff78f8" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#3fc56b" },

	# Fallback
	{ name = "*", fg = "#abb2bf" },
	{ name = "*/", fg = "#3691ff" }
]

# : }}}

