os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
gui:
  showFileTree: false
  scrollHeight: 20
  showIcons: true
  branchColors:
    'main': 'blue'
    'master': 'blue'
    'dev': 'green'
    'develop': 'green'
    'release': 'yellow'
    'hotfix': 'red'
  authorColors:
    '*': 'magenta'
  nerdFontsVersion: "3"
promptToReturnFromSubprocess: false
git:
  overrideGpg: true
